trigger:
- main  # Change this to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate image based on your needs

jobs:
- job: RunPythonScript
  displayName: 'Run Python Script'
  steps:
  - script: |
      python3 -m venv env
      source env/bin/activate
      #pip install -r requirements.txt  # If you have any dependencies
      python HelloTest.py
    displayName: 'Run Python Script'
